name: Release Obsidian plugin

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
            - name: Install dependencies
              run: npm install

            - name: Build plugin
              run: npm run build

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
